// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MyFirstServiceClient is the client API for MyFirstService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyFirstServiceClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	Other(ctx context.Context, in *DataReq, opts ...grpc.CallOption) (*DataRes, error)
}

type myFirstServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyFirstServiceClient(cc grpc.ClientConnInterface) MyFirstServiceClient {
	return &myFirstServiceClient{cc}
}

func (c *myFirstServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/chat.MyFirstService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myFirstServiceClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/chat.MyFirstService/SayHelloAgain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myFirstServiceClient) Other(ctx context.Context, in *DataReq, opts ...grpc.CallOption) (*DataRes, error) {
	out := new(DataRes)
	err := c.cc.Invoke(ctx, "/chat.MyFirstService/Other", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyFirstServiceServer is the server API for MyFirstService service.
// All implementations must embed UnimplementedMyFirstServiceServer
// for forward compatibility
type MyFirstServiceServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
	Other(context.Context, *DataReq) (*DataRes, error)
	mustEmbedUnimplementedMyFirstServiceServer()
}

// UnimplementedMyFirstServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyFirstServiceServer struct {
}

func (UnimplementedMyFirstServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMyFirstServiceServer) SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAgain not implemented")
}
func (UnimplementedMyFirstServiceServer) Other(context.Context, *DataReq) (*DataRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Other not implemented")
}
func (UnimplementedMyFirstServiceServer) mustEmbedUnimplementedMyFirstServiceServer() {}

// UnsafeMyFirstServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyFirstServiceServer will
// result in compilation errors.
type UnsafeMyFirstServiceServer interface {
	mustEmbedUnimplementedMyFirstServiceServer()
}

func RegisterMyFirstServiceServer(s grpc.ServiceRegistrar, srv MyFirstServiceServer) {
	s.RegisterService(&MyFirstService_ServiceDesc, srv)
}

func _MyFirstService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFirstServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.MyFirstService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFirstServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyFirstService_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFirstServiceServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.MyFirstService/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFirstServiceServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyFirstService_Other_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyFirstServiceServer).Other(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.MyFirstService/Other",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyFirstServiceServer).Other(ctx, req.(*DataReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MyFirstService_ServiceDesc is the grpc.ServiceDesc for MyFirstService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyFirstService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.MyFirstService",
	HandlerType: (*MyFirstServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _MyFirstService_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _MyFirstService_SayHelloAgain_Handler,
		},
		{
			MethodName: "Other",
			Handler:    _MyFirstService_Other_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat/chat.proto",
}
